<a href="https://colab.research.google.com/github/putuwinda/DTI_Text-Mining-and-Classification-Hate-Speech-Detection-/blob/main/DTI_Module_7_Text_Mining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [115]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer

from sklearn.naive_bayes import GaussianNB 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn import metrics
from sklearn.metrics import confusion_matrix 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [20]:
!pip install sastrawi

     |████████████████████████████████| 215kB 12.5MB/s 


In [45]:
df_tweet = pd.read_csv('https://raw.githubusercontent.com/ialfina/id-hatespeech-detection/master/IDHSD_RIO_unbalanced_713_2017.txt', sep='\t', encoding = "ISO-8859-1", dtype=str)
df_tweet.head()

Label                                              Tweet
0  Non_HS  RT @spardaxyz: Fadli Zon Minta Mendagri Segera...
1  Non_HS  RT @baguscondromowo: Mereka terus melukai aksi...
2  Non_HS  Sylvi: bagaimana gurbernur melakukan kekerasan...
3  Non_HS  Ahmad Dhani Tak Puas Debat Pilkada, Masalah Ja...
4  Non_HS  RT @lisdaulay28: Waspada KTP palsu.....kawal P...

In [46]:
df_tweet['Label'].value_counts()

Non_HS    453
HS        260
Name: Label, dtype: int64

When we count the value of the data, the value of  non_hs and hs are imbalance, so we need to balance it.

In [47]:
df_tweet.isnull().sum()

Label    0
Tweet    0
dtype: int64

# Data Preprocessing

Data Cleaning

In [65]:
df_tweet['cleaned_tweet'] = df_tweet.Tweet.apply(lambda x: ' '.join([word for word in x.split() if not word.startswith('@')]))

In [74]:

df_tweet['cleaned_tweet'] = df_tweet.Tweet.apply(lambda x: ' '.join([word for word in x.split() if not word.startswith('@')]))
df_tweet['cleaned_tweet'] = df_tweet.Tweet.apply(lambda x: ' '.join([word for word in x.split() if not word.endswith(':')]))

In [75]:
df_tweet_clean = df_tweet.copy()
df_tweet_clean.head()

Label  ...                                      cleaned_tweet
0  Non_HS  ...  RT Fadli Zon Minta Mendagri Segera Menonaktifk...
1  Non_HS  ...  RT Mereka terus melukai aksi dalam rangka meme...
2  Non_HS  ...  bagaimana gurbernur melakukan kekerasan peremp...
3  Non_HS  ...  Ahmad Dhani Tak Puas Debat Pilkada, Masalah Ja...
4  Non_HS  ...  RT Waspada KTP palsu.....kawal PILKADA https:\...

[5 rows x 3 columns]

In [76]:
def case_fold(data):
    return data.str.lower()

In [77]:
df_tweet_clean['cleaned_tweet'] = case_fold(df_tweet_clean['cleaned_tweet'])
df_tweet_clean.head()

Label  ...                                      cleaned_tweet
0  Non_HS  ...  rt fadli zon minta mendagri segera menonaktifk...
1  Non_HS  ...  rt mereka terus melukai aksi dalam rangka meme...
2  Non_HS  ...  bagaimana gurbernur melakukan kekerasan peremp...
3  Non_HS  ...  ahmad dhani tak puas debat pilkada, masalah ja...
4  Non_HS  ...  rt waspada ktp palsu.....kawal pilkada https:\...

[5 rows x 3 columns]

# Vectorization

In [90]:
X = df_tweet_clean['cleaned_tweet']
count_vect = CountVectorizer()
X_train_counts = count_vect.fit_transform(X)
X_train_counts.shape

(713, 3117)

In [95]:
tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape

(713, 3117)

In [97]:
le = LabelEncoder()
y = le.fit_transform(df_tweet_clean['Label'])

In [99]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [103]:
X_train, X_test, y_train, y_test = train_test_split(X_train_tfidf, y, test_size=0.2, random_state=0)

# Classifier

**Naive Bayes**

In [106]:
#classification
clf = GaussianNB()
model = clf.fit(X_train.toarray(), y_train)
y_pred = model.predict(X_test.toarray())

In [107]:
#test the accuracy
accuracy = accuracy_score(y_test, y_pred, normalize = True)
print(accuracy)

0.7482517482517482


In [116]:
# print the Confusion Matrix, Acuracy Score, and Report (precision, recallm f1-score, support)
y_true = y_test
results = confusion_matrix(y_true, y_pred) 
print('Confusion Matrix Naive Bayes Classifier :')
print(results) 
print('Accuracy Score :',accuracy_score(y_true, y_pred))
print('Report : ')
print(classification_report(y_true, y_pred))

Confusion Matrix Naive Bayes Classifier :
[[36 21]
 [15 71]]
Accuracy Score : 0.7482517482517482
Report : 
              precision    recall  f1-score   support

           0       0.71      0.63      0.67        57
           1       0.77      0.83      0.80        86

    accuracy                           0.75       143
   macro avg       0.74      0.73      0.73       143
weighted avg       0.75      0.75      0.75       143



**KNN**

In [109]:
#using the knn to predict the class
model_knn = KNeighborsClassifier(n_neighbors=5)
model_knn.fit(X_train.toarray(), y_train)
y_pred_knn = model_knn.predict(X_test.toarray())
#return the prediction
y_pred_knn

array([1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1])

In [110]:
#test the accuracy
accuracy = accuracy_score(y_test, y_pred_knn, normalize = True)
print(accuracy)

0.7762237762237763


In [117]:
#print the Confusion Matrix, Acuracy Score, and Report (precision, recallm f1-score, support)
y_true = y_test
results = confusion_matrix(y_true, y_pred_knn) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y_true, y_pred_knn))
print('Report : ')
print(classification_report(y_true, y_pred_knn))

Confusion Matrix :
[[35 22]
 [10 76]]
Accuracy Score : 0.7762237762237763
Report : 
              precision    recall  f1-score   support

           0       0.78      0.61      0.69        57
           1       0.78      0.88      0.83        86

    accuracy                           0.78       143
   macro avg       0.78      0.75      0.76       143
weighted avg       0.78      0.78      0.77       143



**Random Forest**

In [111]:
model_rf = RandomForestClassifier(max_depth=10, random_state=1)
model_rf.fit(X_train.toarray(), y_train)
y_pred_rf = model_rf.predict(X_test.toarray())
y_pred_rf

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0])

In [112]:
#test the accuracy
accuracy = accuracy_score(y_test, y_pred_rf, normalize = True)
print(accuracy)

0.7412587412587412


In [118]:
#print the Confusion Matrix, Acuracy Score, and Report (precision, recallm f1-score, support)
y_true = y_test
results = confusion_matrix(y_true, y_pred_rf) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y_true, y_pred_rf))
print('Report : ')
print(classification_report(y_true, y_pred_rf))

Confusion Matrix :
[[20 37]
 [ 0 86]]
Accuracy Score : 0.7412587412587412
Report : 
              precision    recall  f1-score   support

           0       1.00      0.35      0.52        57
           1       0.70      1.00      0.82        86

    accuracy                           0.74       143
   macro avg       0.85      0.68      0.67       143
weighted avg       0.82      0.74      0.70       143



# Comparison between accuracy

In [119]:
result_class = pd.DataFrame({
    'True Predictions': y_true,
    'Naive Bayes': y_pred,
    'KNN' : y_pred_knn,
    'Random Forest' : y_pred_rf
})

result_class

True Predictions  Naive Bayes  KNN  Random Forest
0                   1            1    1              1
1                   1            1    1              1
2                   1            1    1              1
3                   1            1    1              1
4                   0            1    1              1
..                ...          ...  ...            ...
138                 0            1    0              1
139                 0            1    0              0
140                 1            1    1              1
141                 1            0    0              1
142                 0            1    1              0

[143 rows x 4 columns]